# Generated by Django 4.2.11 on 2025-09-17 05:30

from django.db import migrations
from django.contrib.auth import get_user_model

def create_default_superuser(apps, schema_editor):
    User = get_user_model()
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser('admin', 'admin@example.com', 'password123')

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_default_superuser),
    ]


